### ISSUE TITLE
Heroku endpoint isn't working anymore ...

### ISSUE THREAD

**Issue by weeping-angel** [akashrchandran/Rayso-API#3]

**Comment by akashrchandran** [comment]
Heroku stopped the free tier. Will need to find a new hosting service and it seems the code is broken, will fix that too.

**Comment by infofbnr** [comment]
please fix it. maybe make new account or something. Use github pages for hosting or netlify

**Comment by dev-abhi89** [comment]
any update?  this code is still not working

**Comment by akashrchandran** [comment]
> any update? this code is still not working

It's sorted now. Please take a look.
